name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

change-template: "- $TITLE by @$AUTHOR in [#$NUMBER]($URL)"

# バージョン管理設定
version-resolver:
    major:
        labels:
            - "major"
    minor:
        labels:
            - "minor"
    patch:
        labels:
            - "patch"
    default: "minor" # ラベル無しのPRはマイナーバージョンをインクリメント

# リリースノートのテンプレート
template: |
    ## What's Changed

    $CHANGES

    **Full Changelog**: `[$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)`
