# コードのチェックを実行するワークフロー

name: Code Check
on: push

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: Format
              run: npm run fmt:check

            - name: Lint
              run: npm run lint

            - name: Type Check
              run: npm run check

            - name: Build
              run: npm run build
