# mainブランチが更新されたときに、リリース準備のPRを作成するワークフロー

name: Prepare Next Release

on:
    push:
        branches:
            - main

env:
    # バージョンのアップデート作業を行うブランチ名
    BRANCH_NAME: auto/bump-version

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: prepare-next-release

jobs:
    check-status:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            # 既にpackage.jsonのバージョンが上がっているかどうか
            # 既に上がっている場合はPRを作成せずに終了
            - name: Check if release is ready
              id: check-release-ready
              uses: ./.github/actions/check-release-ready

            # 既にpackage.jsonのバージョンを上げるPRが存在しているかどうか
            # 既に存在している場合はPRを作成せずに終了
            - name: Check if PR already exists
              id: check-pr-exists
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --base main --state open --json number --jq '.[0].number // empty')
                  echo "pr-number=$PR_NUMBER" >> $GITHUB_OUTPUT

        outputs:
            should-create-pr: ${{ case(steps.check-release-ready.outputs.ready == 'true' && steps.check-pr-exists.outputs.pr-number == '', 'true', 'false') }}

    create-pr:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        needs: check-status
        if: needs.check-status.outputs.should-create-pr == 'true'

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: ./.github/actions/setup-node

            - name: Setup Git user
              uses: ./.github/actions/setup-git-user

            - name: Bump Version
              id: bump-version
              # package.jsonのバージョンを上げる（Gitのタグは作成しない）
              run: |
                  NEW_VERSION=$(npm version minor --no-git-tag-version)
                  echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT

            - name: Create Pull Request
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PR_TITLE: "Release ${{ steps.bump-version.outputs.new-version }}"
                  PR_BODY: |
                      ${{ steps.bump-version.outputs.new-version }}をリリースします。

                      > [!NOTE]
                      > このプルリクエストをマージすると、自動で新しいバージョンが公開されます。
              run: |
                  git switch -c "$BRANCH_NAME"
                  git add package.json package-lock.json
                  git commit -m "chore: bump version"
                  git push -f origin "$BRANCH_NAME"

                  gh pr create \
                      --title "$PR_TITLE" \
                      --body "$PR_BODY" \
                      --base main \
                      --head "$BRANCH_NAME"
